spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update

tourapi.key=

azure.openai.endpoint=
azure.openai.api-key=
azure.openai.deployment=gpt-4o-mini
azure.openai.api-version=2025-01-01-preview
kakao.api-key=
weather.api.key=
